[package]
name = "noodles-gff"
version = "0.19.1"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "Generic Feature Format (GFF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gff"

[dependencies]
indexmap.workspace = true
noodles-bgzf = { path = "../noodles-bgzf", version = "0.23.0" }
noodles-core = { path = "../noodles-core", version = "0.12.0" }
noodles-csi = { path = "../noodles-csi", version = "0.23.0" }
percent-encoding.workspace = true
