[package]
name = "noodles-gtf"
version = "0.20.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "Gene Transfer Format (GTF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gtf"

[dependencies]
noodles-bgzf = { path = "../noodles-bgzf", version = "0.25.0" }
noodles-core = { path = "../noodles-core", version = "0.12.0" }
noodles-csi = { path = "../noodles-csi", version = "0.27.0" }
